{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "newweb.serviceAccountName" . }}
  labels:
{{ include "newweb.labels" . | nindent 4 }}
{{- end -}}
