---
- name: Start CICD instance
  hosts: localhost
  gather_facts: false
  vars:
    instance_ids:
      - 'i-07844ade7914f7747'
    region: us-east-2
  tasks:
    - name: Start the instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: running
        wait: True
        vpc_subnet_id: subnet-8ec584e7
      register: myec2

    - debug: 
        var: myec2.instances[0].public_ip
    - debug: 
        var: myec2

    - name: change route 53 hosted zone record
      route53:
        state: present
        zone: design4dong.com
        record: web.design4dong.com
        type: A
        ttl: 7200
        value: "{{myec2.instances[0].public_ip}}"
        wait: yes
        overwrite: yes
      register: mydns

    - debug:
        var: mydns

# - name: download git repo and run terraform in the shell
#   hosts: us-east-2
#   gather_facts: false
#   remote_user: ubuntu
#   become: yes
  
#   tasks:

#     - name: download repo from git
#       git:
#         repo: 'https://github.com/JimZhang37/cloud-devops-project-5-capstone.git'
#         dest: /repo/
#       register: repo

#     - debug: 
#         var: repo
    
#     - name: run terraform apply
#       terraform:
#         project_path: 'cloud-devops-project-5-capstone/1 terraform'
#         state: present
#       register: terraform

#     - debug:
#         var: terraform.outputs.kubeconfig.value

#     - name: save kubectl config 
#       copy:
#         content: '{{terraform.outputs.kubeconfig.value}}'
#         dest: /home/ubuntu/.kube/config
        
