---
- name: save kubectl
  hosts: us-east-2
  gather_facts: false
  remote_user: ubuntu
  become: yes
  
  tasks:

    - name: run terraform script
      terraform:
        project_path: 'cloud-devops-project-5-capstone/1 terraform'
        state: absent
      register: terraform

    - debug:
        var: terraform

    # - name: save kubeconfig
    #   command: 
    #     cmd: terraform output kubeconfig>~/.kube/config
    #     chdir: 'cloud-devops-project-5-capstone/1 terraform'
    #   register: output2

    # - debug:
    #     var: output2
    # - name: change route 53 hosted zone record
    #   route53:
    #     state: present
    #     zone: design4dong.com
    #     record: web.design4dong.com
    #     type: A
    #     ttl: 7200
    #     value: "{{myec2.instances[0].public_ip}}"
    #     wait: yes
    #   register: mydns

    # - debug:
    #     var: mydns
